### ISSUE TITLE
Issue: when deleting NetworkPolicy, got Error: Network policy enforcement local IP is missing or non-string

### ISSUE THREAD

**Issue by Hong-Chang** [CentaurusInfra/mizar#379]
Repro steps:
1. Create a policy
2. delete a policy

Error message:
[2021-01-14 01:37:59,006] luigi-interface      [INFO    ] [pid 7] Worker Worker(salt=655306544, workers=1, host=kind-worker2, username=root, pid=7) running   k8sNetworkPolicyDelete(param=<mizar.common.wf_param.HandlerParam object at 0x7f59c4a341f0>)
[2021-01-14 01:37:59,006] root                 [INFO    ] Requires k8sNetworkPolicyDelete
[2021-01-14 01:37:59,006] root                 [INFO    ] Run k8sNetworkPolicyDelete
[2021-01-14 01:37:59,007] root                 [INFO    ] delete_network_policy_enforcement_map_ingress: /trn_bin/transit -s 172.18.0.4  delete-net-policy-enforce-in -i eth0 -j '{"tunnel_id": "1", "ip": "20.0.0.25"}'
[2021-01-14 01:37:59,031] root                 [INFO    ] delete_network_policy_enforcement_map_ingress returns None Error: Network policy enforcement local IP is missing or non-string
Error: parsing network policy enforcement config.

=================================================================
==412==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x564e910eb5a5 in __interceptor_malloc (/var/mizar/build/bin/transit+0x235a5)
    #1 0x564e91139b22 in cJSON_New_Item src/extern/cJSON.c:214
    #2 0x564e91139b22 in cJSON_ParseWithOpts src/extern/cJSON.c:1029
    #3 0x564e91139b22 in cJSON_Parse src/extern/cJSON.c:1092
    #4 0x564e9111f287 in trn_cli_parse_json src/cli/trn_cli_common.c:29
    #5 0x564e911285c8 in trn_cli_delete_transit_network_policy_enforcement_subcmd src/cli/trn_cli_network_policy.c:445
    #6 0x564e910e2e15 in main src/cli/trn_cli.c:135
    #7 0x7f0810a8509a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 128 byte(s) in 2 object(s) allocated from:
    #0 0x564e910eb5a5 in __interceptor_malloc (/var/mizar/build/bin/transit+0x235a5)
    #1 0x564e9113684f in cJSON_New_Item src/extern/cJSON.c:214
    #2 0x564e9113684f in parse_object src/extern/cJSON.c:1543
    #3 0x564e9113684f in parse_value src/extern/cJSON.c:1270
    #4 0x564e91139c6c in cJSON_ParseWithOpts src/extern/cJSON.c:1035
    #5 0x564e91139c6c in cJSON_Parse src/extern/cJSON.c:1092
    #6 0x564e9111f287 in trn_cli_parse_json src/cli/trn_cli_common.c:29
    #7 0x564e911285c8 in trn_cli_delete_transit_network_policy_enforcement_subcmd src/cli/trn_cli_network_policy.c:445
    #8 0x564e910e2e15 in main src/cli/trn_cli.c:135
    #9 0x7f0810a8509a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 15 byte(s) in 2 object(s) allocated from:
    #0 0x564e910eb5a5 in __interceptor_malloc (/var/mizar/build/bin/transit+0x235a5)
    #1 0x564e9112fa8d in parse_string src/extern/cJSON.c:747
    #2 0x564e9113656a in parse_object src/extern/cJSON.c:1566
    #3 0x564e9113656a in parse_value src/extern/cJSON.c:1270
    #4 0x564e91139c6c in cJSON_ParseWithOpts src/extern/cJSON.c:1035
    #5 0x564e91139c6c in cJSON_Parse src/extern/cJSON.c:1092
    #6 0x564e9111f287 in trn_cli_parse_json src/cli/trn_cli_common.c:29
    #7 0x564e911285c8 in trn_cli_delete_transit_network_policy_enforcement_subcmd src/cli/trn_cli_network_policy.c:445
    #8 0x564e910e2e15 in main src/cli/trn_cli.c:135
    #9 0x7f0810a8509a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 14 byte(s) in 2 object(s) allocated from:
    #0 0x564e910eb5a5 in __interceptor_malloc (/var/mizar/build/bin/transit+0x235a5)
    #1 0x564e9112fa8d in parse_string src/extern/cJSON.c:747
    #2 0x564e91136142 in parse_value src/extern/cJSON.c:1255
    #3 0x564e91136728 in parse_object src/extern/cJSON.c:1584
    #4 0x564e91136728 in parse_value src/extern/cJSON.c:1270
    #5 0x564e91139c6c in cJSON_ParseWithOpts src/extern/cJSON.c:1035
    #6 0x564e91139c6c in cJSON_Parse src/extern/cJSON.c:1092
    #7 0x564e9111f287 in trn_cli_parse_json src/cli/trn_cli_common.c:29
    #8 0x564e911285c8 in trn_cli_delete_transit_network_policy_enforcement_subcmd src/cli/trn_cli_network_policy.c:445
    #9 0x564e910e2e15 in main src/cli/trn_cli.c:135
    #10 0x7f0810a8509a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: LeakSanitizer: 221 byte(s) leaked in 7 allocation(s).

**Comment by Hong-Chang** [comment]
Not repro any more.
