### ISSUE TITLE
Pod creation stuck in ContainerCreating state

### ISSUE THREAD

**Issue by click2cloud-amit** [CentaurusInfra/mizar#436]
In an Arktos & Mizar environment, while creating a pod, the pod stuck in ContainerCreating state for very long time.

- Deploy the Arktos cluster
- Deploy the Arktos Network controller
- Deploy the Mizar
- Try to create a pod

**Following is the mizar-operator log:**

[2021-02-18 02:35:55,080] root                 [INFO    ] TaskName: k8sDropletCreate Name:  Return code is: 0 Return message is: OK
[2021-02-18 02:36:35,456] root                 [INFO    ] Creating pod from Arktos Service amit-pod-30
[2021-02-18 02:36:35,461] luigi                [INFO    ] logging already configured
[2021-02-18 02:36:35,467] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,482] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_27c7fe84e1   has status   PENDING
[2021-02-18 02:36:35,482] luigi-interface      [INFO    ] Done scheduling tasks
[2021-02-18 02:36:35,483] luigi-interface      [INFO    ] Running Worker with 1 processes
[2021-02-18 02:36:35,489] root                 [INFO    ] Creating pod from Arktos Service amit-pod-30
[2021-02-18 02:36:35,494] luigi                [INFO    ] logging already configured
[2021-02-18 02:36:35,515] luigi-interface      [INFO    ] [pid 6] Worker Worker(salt=478044369, workers=1, host=centaurus-master, username=root, pid=6) ru                                                                                nning   k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a86839d0>)
[2021-02-18 02:36:35,516] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,516] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,516] root                 [INFO    ] Creating pod from Arktos Service amit-pod-30
[2021-02-18 02:36:35,521] root                 [INFO    ] Run k8sPodCreate
[2021-02-18 02:36:35,524] luigi                [INFO    ] logging already configured
[2021-02-18 02:36:35,525] root                 [INFO    ] Pod spec {'hostIP': '', 'name': 'amit-pod-30', 'type': 'kubernetes', 'namespace': 'default', 'te                                                                                nant': 'system', 'vpc': 'vpc0', 'subnet': 'net0', 'phase': 'Pending', 'interfaces': [{'name': 'eth0'}]}
[2021-02-18 02:36:35,527] luigi-interface      [ERROR   ] [pid 6] Worker Worker(salt=478044369, workers=1, host=centaurus-master, username=root, pid=6) fa                                                                                iled    k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a86839d0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/usr/local/lib/python3.8/site-packages/mizar/dp/mizar/workflows/builtins/pods/create.py", line 103, in run
    self.raise_temporary_error("Droplet not yet created.")
  File "/usr/local/lib/python3.8/site-packages/mizar/common/workflow.py", line 45, in raise_temporary_error
    raise Exception(self.error_message)
Exception: Droplet not yet created.
[2021-02-18 02:36:35,533] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,539] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_b8654267db   has status   PENDING
[2021-02-18 02:36:35,540] luigi-interface      [INFO    ] Done scheduling tasks
[2021-02-18 02:36:35,540] luigi-interface      [INFO    ] Running Worker with 1 processes
[2021-02-18 02:36:35,561] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_27c7fe84e1   has status   FAILED
[2021-02-18 02:36:35,565] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_0c84a1f989   has status   PENDING
[2021-02-18 02:36:35,565] luigi-interface      [INFO    ] Done scheduling tasks
[2021-02-18 02:36:35,565] luigi-interface      [INFO    ] Running Worker with 1 processes
[2021-02-18 02:36:35,569] luigi-interface      [INFO    ] [pid 6] Worker Worker(salt=617056708, workers=1, host=centaurus-master, username=root, pid=6) ru                                                                                nning   k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a8695ca0>)
[2021-02-18 02:36:35,569] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,570] root                 [INFO    ] Run k8sPodCreate
[2021-02-18 02:36:35,570] root                 [INFO    ] Pod spec {'hostIP': '', 'name': 'amit-pod-30', 'type': 'kubernetes', 'namespace': 'default', 'te                                                                                nant': 'system', 'vpc': 'vpc0', 'subnet': 'net0', 'phase': 'Pending', 'interfaces': [{'name': 'eth0'}]}
[2021-02-18 02:36:35,571] luigi-interface      [ERROR   ] [pid 6] Worker Worker(salt=617056708, workers=1, host=centaurus-master, username=root, pid=6) fa                                                                                iled    k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a8695ca0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/usr/local/lib/python3.8/site-packages/mizar/dp/mizar/workflows/builtins/pods/create.py", line 103, in run
    self.raise_temporary_error("Droplet not yet created.")
  File "/usr/local/lib/python3.8/site-packages/mizar/common/workflow.py", line 45, in raise_temporary_error
    raise Exception(self.error_message)
Exception: Droplet not yet created.
[2021-02-18 02:36:35,577] luigi-interface      [INFO    ] Worker Worker(salt=478044369, workers=1, host=centaurus-master, username=root, pid=6) was stoppe                                                                                d. Shutting down Keep-Alive thread
[2021-02-18 02:36:35,580] luigi-interface      [INFO    ]
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a86839d0>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,580] root                 [INFO    ] Temporary Error: Droplet not yet created.
[2021-02-18 02:36:35,581] root                 [INFO    ] TaskName: k8sPodCreate Name: amit-pod-30 Return code is: 1 Return message is: Droplet not yet cr                                                                                eated.
[2021-02-18 02:36:35,582] luigi-interface      [INFO    ] [pid 6] Worker Worker(salt=752164514, workers=1, host=centaurus-master, username=root, pid=6) ru                                                                                nning   k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a87a2d60>)
[2021-02-18 02:36:35,585] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,585] root                 [INFO    ] Run k8sPodCreate
[2021-02-18 02:36:35,585] root                 [INFO    ] Pod spec {'hostIP': '192.168.3.15', 'name': 'amit-pod-30', 'type': 'kubernetes', 'namespace': 'd                                                                                efault', 'tenant': 'system', 'vpc': 'vpc0', 'subnet': 'net0', 'phase': 'Pending', 'interfaces': [{'name': 'eth0'}]}
[2021-02-18 02:36:35,586] root                 [INFO    ] init_simple_endpoint_interface 192.168.3.15
[2021-02-18 02:36:35,599] root                 [INFO    ] Create simple endpoint interface_id {
  pod_id {
    k8s_pod_name: "amit-pod-30"
    k8s_namespace: "default"
    k8s_pod_tenant: "system"
  }
  interface: "eth0"
}
veth {
  name: "eth-c486fc02"
  peer: "veth-c486fc02"
}
address {
  mac: "16:ab:cb:fa:64:9a"
}

[2021-02-18 02:36:35,600] root                 [INFO    ] EP already exists!
[2021-02-18 02:36:35,600] luigi-interface      [ERROR   ] [pid 6] Worker Worker(salt=752164514, workers=1, host=centaurus-master, username=root, pid=6) fa                                                                                iled    k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a87a2d60>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/usr/local/lib/python3.8/site-packages/mizar/dp/mizar/workflows/builtins/pods/create.py", line 114, in run
    networkpolicy_util.handle_pod_change_for_networkpolicy(self.param.name, self.param.namespace, self.param.diff)
AttributeError: 'HandlerParam' object has no attribute 'namespace'
[2021-02-18 02:36:35,602] root                 [INFO    ] Creating pod from Arktos Service amit-pod-30
[2021-02-18 02:36:35,606] luigi                [INFO    ] logging already configured
[2021-02-18 02:36:35,608] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_b8654267db   has status   FAILED
[2021-02-18 02:36:35,619] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,637] luigi-interface      [INFO    ] Worker Worker(salt=617056708, workers=1, host=centaurus-master, username=root, pid=6) was stoppe                                                                                d. Shutting down Keep-Alive thread
[2021-02-18 02:36:35,640] luigi-interface      [INFO    ]
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a8695ca0>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,642] root                 [INFO    ] Temporary Error: Droplet not yet created.
[2021-02-18 02:36:35,642] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_8d4245b231   has status   PENDING
[2021-02-18 02:36:35,643] root                 [INFO    ] TaskName: k8sPodCreate Name: amit-pod-30 Return code is: 1 Return message is: Droplet not yet cr                                                                                eated.
[2021-02-18 02:36:35,646] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_0c84a1f989   has status   FAILED
[2021-02-18 02:36:35,647] luigi-interface      [INFO    ] Done scheduling tasks
[2021-02-18 02:36:35,652] luigi-interface      [INFO    ] Running Worker with 1 processes
[2021-02-18 02:36:35,657] luigi-interface      [INFO    ] Worker Worker(salt=752164514, workers=1, host=centaurus-master, username=root, pid=6) was stoppe                                                                                d. Shutting down Keep-Alive thread
[2021-02-18 02:36:35,660] luigi-interface      [INFO    ]
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a87a2d60>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,661] root                 [INFO    ] Creating pod from Arktos Service amit-pod-30
[2021-02-18 02:36:35,661] root                 [INFO    ] Unknown Error:
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a87a2d60>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,669] luigi                [INFO    ] logging already configured
[2021-02-18 02:36:35,670] root                 [INFO    ] TaskName: k8sPodCreate Name: amit-pod-30 Return code is: 2 Return message is:
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6a87a2d60>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,675] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,678] luigi-interface      [INFO    ] [pid 6] Worker Worker(salt=637018465, workers=1, host=centaurus-master, username=root, pid=6) ru                                                                                nning   k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80f3970>)
[2021-02-18 02:36:35,683] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,683] root                 [INFO    ] Run k8sPodCreate
[2021-02-18 02:36:35,684] root                 [INFO    ] Pod spec {'hostIP': '192.168.3.15', 'name': 'amit-pod-30', 'type': 'kubernetes', 'namespace': 'd                                                                                efault', 'tenant': 'system', 'vpc': 'vpc0', 'subnet': 'net0', 'phase': 'Pending', 'interfaces': [{'name': 'eth0'}]}
[2021-02-18 02:36:35,684] root                 [INFO    ] init_simple_endpoint_interface 192.168.3.15
[2021-02-18 02:36:35,688] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_a839058d2d   has status   PENDING
[2021-02-18 02:36:35,689] luigi-interface      [INFO    ] Done scheduling tasks
[2021-02-18 02:36:35,689] luigi-interface      [INFO    ] Running Worker with 1 processes
[2021-02-18 02:36:35,696] root                 [INFO    ] Create simple endpoint interface_id {
  pod_id {
    k8s_pod_name: "amit-pod-30"
    k8s_namespace: "default"
    k8s_pod_tenant: "system"
  }
  interface: "eth0"
}
veth {
  name: "eth-c486fc02"
  peer: "veth-c486fc02"
}
address {
  mac: "16:ab:cb:fa:64:9a"
}

[2021-02-18 02:36:35,699] root                 [INFO    ] EP already exists!
[2021-02-18 02:36:35,700] luigi-interface      [ERROR   ] [pid 6] Worker Worker(salt=637018465, workers=1, host=centaurus-master, username=root, pid=6) fa                                                                                iled    k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80f3970>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/usr/local/lib/python3.8/site-packages/mizar/dp/mizar/workflows/builtins/pods/create.py", line 114, in run
    networkpolicy_util.handle_pod_change_for_networkpolicy(self.param.name, self.param.namespace, self.param.diff)
AttributeError: 'HandlerParam' object has no attribute 'namespace'
[2021-02-18 02:36:35,717] luigi-interface      [INFO    ] [pid 6] Worker Worker(salt=087480931, workers=1, host=centaurus-master, username=root, pid=6) ru                                                                                nning   k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80c66a0>)
[2021-02-18 02:36:35,718] root                 [INFO    ] Requires k8sPodCreate
[2021-02-18 02:36:35,718] root                 [INFO    ] Run k8sPodCreate
[2021-02-18 02:36:35,720] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_8d4245b231   has status   FAILED
[2021-02-18 02:36:35,720] root                 [INFO    ] Pod spec {'hostIP': '192.168.3.15', 'name': 'amit-pod-30', 'type': 'kubernetes', 'namespace': 'd                                                                                efault', 'tenant': 'system', 'vpc': 'vpc0', 'subnet': 'net0', 'phase': 'Pending', 'interfaces': [{'name': 'eth0'}]}
[2021-02-18 02:36:35,723] root                 [INFO    ] init_simple_endpoint_interface 192.168.3.15
[2021-02-18 02:36:35,739] root                 [INFO    ] Create simple endpoint interface_id {
  pod_id {
    k8s_pod_name: "amit-pod-30"
    k8s_namespace: "default"
    k8s_pod_tenant: "system"
  }
  interface: "eth0"
}
veth {
  name: "eth-c486fc02"
  peer: "veth-c486fc02"
}
address {
  mac: "16:ab:cb:fa:64:9a"
}

[2021-02-18 02:36:35,740] root                 [INFO    ] EP already exists!
[2021-02-18 02:36:35,740] luigi-interface      [ERROR   ] [pid 6] Worker Worker(salt=087480931, workers=1, host=centaurus-master, username=root, pid=6) fa                                                                                iled    k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80c66a0>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/usr/local/lib/python3.8/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/usr/local/lib/python3.8/site-packages/mizar/dp/mizar/workflows/builtins/pods/create.py", line 114, in run
    networkpolicy_util.handle_pod_change_for_networkpolicy(self.param.name, self.param.namespace, self.param.diff)
AttributeError: 'HandlerParam' object has no attribute 'namespace'
[2021-02-18 02:36:35,740] luigi-interface      [INFO    ] Worker Worker(salt=637018465, workers=1, host=centaurus-master, username=root, pid=6) was stoppe                                                                                d. Shutting down Keep-Alive thread
[2021-02-18 02:36:35,744] luigi-interface      [INFO    ]
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80f3970>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,744] root                 [INFO    ] Unknown Error:
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80f3970>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,744] root                 [INFO    ] TaskName: k8sPodCreate Name: amit-pod-30 Return code is: 2 Return message is:
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80f3970>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,759] luigi-interface      [INFO    ] Informed scheduler that task   k8sPodCreate__mizar_common_wf_a839058d2d   has status   FAILED
[2021-02-18 02:36:35,766] luigi-interface      [INFO    ] Worker Worker(salt=087480931, workers=1, host=centaurus-master, username=root, pid=6) was stoppe                                                                                d. Shutting down Keep-Alive thread
[2021-02-18 02:36:35,768] luigi-interface      [INFO    ]
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80c66a0>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,768] root                 [INFO    ] Unknown Error:
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80c66a0>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

[2021-02-18 02:36:35,768] root                 [INFO    ] TaskName: k8sPodCreate Name: amit-pod-30 Return code is: 2 Return message is:
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 failed:
    - 1 k8sPodCreate(param=<mizar.common.wf_param.HandlerParam object at 0x7fa6b80c66a0>)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

**Comment by vinaykul** [comment]
@click2cloud-akshay @click2cloud-amit Please verify this particular issue has been fixed and close. And please create a new issue for the current pod-create failure.

**Comment by click2cloud-amit** [comment]
As Hong mentioned earlier, the namespace error is fixed and we don't see any error related to namespace in the logs.
Hence we are closing this issue.
